version: "3"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: '1@mChampHealth'
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"
      # If you are on Linux, host.docker.internal might not work by default.
      # You might need to add: extra_hosts: - "host.docker.internal:host-gateway"
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
